export enum Color {
  primary = "#7B61FF",
  primaryLight = "#917CFF",
  secondary = "#80858B",
  black = "#000",
  dark = "#242426",
  graphite = "#323537",
  error = "#FF5154",
  light = "#AFB2B6",
  white = "#fff",
  green = "#00A340",
  yellow = "#F3A608",
  orange = "#F45D2D",
  primary_text = "var(--primary-text)",
  secondary_text = "var(--secondary-text)",
  primary_bg = "var(--primary-bg)",
  secondary_bg = "var(--secondary-bg)",
  block_bg = "var(--block-bg)",
  input_bg = "var(--input_bg)",
  outline_bg = "var(--outline_bg)",
  showMore_bg = "var(--showMore_bg)",
  fill_bg = "var(--fill_bg)",
  wrap_bg = "var(--wrap-bg)",
  logo_bg = "var(--logo_bg)",
}
